### PR TITLE
Fix GPL graphic in Readme

### PR DESCRIPTION
**Pull request by duhow**
This project is supposed to be using the GPL v3 license, not the AGPL v3.

### CODE REVIEW

**Comment by LucasKovacs** [comment]
@duhow please request merges to development

**Comment by duhow** [comment]
@LucasKovacs updated target branch to development.

**Comment by LucasKovacs** [comment]
@duhow what's the problem with the current logo?

**Comment by duhow** [comment]
Ummm... GPL is **completely different** to AGPL. As project uses GPL you must use a image that mentions it specifically.
Unless you just like the colors, then just draw another image.

**Review by LucasKovacs — APPROVED** [review]
LGTM

**Pull request merged**
