### PR TITLE
fix cs

### PR DESCRIPTION
**Pull request by ProPheT777**
Using : https://github.com/FriendsOfPHP/PHP-CS-Fixer

with config : 

```php
<?php

return Symfony\CS\Config\Config::create()
    ->level(Symfony\CS\FixerInterface::SYMFONY_LEVEL)
    ->fixers(array(
	'-psr0',
        'ordered_use',
        'concat_with_spaces',
        'header_comment',
        'newline_after_open_tag',
        'phpdoc_order',
	'align_double_arrow',
	'align_equals'
    ))
    ->finder(
        Symfony\CS\Finder\DefaultFinder::create()
            ->exclude('vendor')
	    ->name('*.php')
            ->in(__DIR__.'/upload')
    )
;
```

### CODE REVIEW

**Comment by athk** [comment]
Should `src/xgp3.0.0/.php_cs` be there

**Comment by ProPheT777** [comment]
I should not be upload on server and should also be versionned in order to everybody have the same configuration, so IMO it's the best option.

**Comment by ProPheT777** [comment]
Moreover if you want to merge this PR, you should merge all other PR and commit & push your local work until you merge it or everybody go to running into insane conflict. 

It's easy for me I just have to revert and re run the tool

**Comment by XGProyect** [comment]
This branch has conflicts, but please ignore. I'm applying PSR-2 whil I review all the code. 75% progress already.

**Pull request closed without merging**
