### PR TITLE
Script install XG Proyect

### PR DESCRIPTION
**Pull request by duhow**
This script will automatically install XG Proyect by calling the specified server URL and variables for MySQL and admin user.

### CODE REVIEW

**Comment by FGServers** [comment]
El instalador creo q debería seguir siendo en php, esta bueno probar otros formatos, lo bueno que debería estar el instalador es separarlo del núcleo algo como Prestashop que si no borras la carpetas install no deja ingresar al admin panel.

**Comment by duhow** [comment]
Si, se podría hacer un CLI de install.php para el propio servidor y que hiciese la instalación ahi mismo. Habrá que evaluar cómo hacerlo pues.

Este script lo tuve que montar (al menos) para inicializar la base de datos a la hora de hacer los tests que ya estaban funcionando... y aun así sigo con problemas. 😂

**Comment by LucasKovacs** [comment]
Why’d you run this instead of the regular installer?

**Comment by LucasKovacs** [comment]
Also the current installer, is not that good, I have to admit that it is not my best job. It will be rewritten XGP 4

**Comment by duhow** [comment]
> Why’d you run this instead of the regular installer?

I wanted to setup the database and config after running Docker XG Proyect, so I wrote this script to perform the automatic install.
Main purpose was an attempt to test phpcompatinfo that somehow, was requiring to use a database, and I thought it was trying to use the game database, so I had to automate the setup to fill in the database data. Still it didn't work.

This script is just something I wrote to get it done, can be replaced with a full PHP CLI application to setup as well.

**Comment by LucasKovacs** [comment]
That’s a problem with phpcompatinfo itself. I have reported the issue, an the author gave a possible solution. I will test it out. Not sure how you did it, but you can try to re enable the script

**Comment by LucasKovacs** [comment]
For reference https://github.com/llaville/php-compatinfo/issues/315#issuecomment-1003427650

**Pull request closed without merging**
