### PR TITLE
Fix database error displayed to user when banned

### LINKED ISSUE #428: [3.3.0-1244] Database error displayed to user when banned
**Describe the bug**
Unexpected error on PHP regarding database connection? 

**To Reproduce**
- Ban user via database
```sql
UPDATE users SET user_banned = UNIX_TIMESTAMP("2020-11-16 00:46:58")
```
- Login

image
 
 **Server:**
- Docker files from project
- XGProyect ac501997d35523b86be88e680dbd70a831b58fc4

### PR DESCRIPTION
**Pull request by duhow**
Fixes #428

### CODE REVIEW

**Comment by LucasKovacs** [comment]
@duhow I will explore other options, since I think this PR patches a flow issue. There has to be another solution. I might even create a controller for it if needed.

**Comment by duhow** [comment]
The thing is, when calling the `die` function to display the ban message, `Session` object launches function `__destruct`, which will update Session in Database via the **write** function `insertNewSessionData`.

As the object is already destroyed, Database **$connection** is null, and the error is displayed.
That's why I'm calling this function right before the object is destroyed.

**Comment by LucasKovacs** [comment]
@duhow I have approved this but this is something to improve.

**Comment by LucasKovacs** [comment]
@duhow take a look... there's always a way :)

https://github.com/XGProyect/XG-Proyect-v3.x.x/commit/aa93d27be25fa239c540b0d9dd2b6d9b979d1131

**Pull request merged**
