### PR TITLE
Use single Dockerfile with PHP version as build args

### PR DESCRIPTION
**Pull request by duhow**
In order to build other PHP versions, run:

```sh
docker build -t xgproyect:7.4 --build-arg=PHP_VERSION=7.4 .
```

### CODE REVIEW

**Comment by LucasKovacs** [comment]
lgtm

**Comment by LucasKovacs** [comment]
@duhow just noticed that there are some issues with the packages while installing 7.4

**Comment by duhow** [comment]
Yep - https://github.com/docker-library/php/issues/931#issuecomment-568658449

**Comment by LucasKovacs** [comment]
Yes I saw that, but while it is for 7.4 it is not for 7.3

**Comment by LucasKovacs** [comment]
I should say it works for 7.4 and above. Not for 7.3

**Comment by duhow** [comment]
```diff
diff --git a/Dockerfile b/Dockerfile
index 0f2519e7..93cb0485 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -13,7 +13,8 @@ RUN set -ex; \
                libzip-dev \
        ; \
        \
-       docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr; \
+       (docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr || \
+       docker-php-ext-configure gd --with-jpeg); \
        docker-php-ext-install gd mysqli opcache zip; \
        \
 # reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
```

**Comment by LucasKovacs** [comment]
Thanks, this was a great addition

**Pull request merged**
